# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codereview',
            options={'ordering': ['-developer'], 'verbose_name': 'Code Review Record'},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['-sprint_start_date'], 'verbose_name': 'Sprint'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='assigned_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_datetime',
            field=models.DateTimeField(),
        ),
    ]
