# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20160119_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffortRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('peer_review_date', models.DateTimeField()),
                ('internal_qa_date', models.DateTimeField()),
                ('client_review_date', models.DateTimeField()),
                ('code_merge_date', models.DateTimeField()),
                ('qa_testing', models.DateTimeField()),
                ('closed', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Effort Record',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EffortTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_effort', models.IntegerField(max_length=1)),
                ('effort_date', models.DateField()),
                ('effort_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.EffortRecord')),
            ],
            options={
                'verbose_name': 'Effort Tracking',
                'ordering': ['-effort_date'],
            },
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Development', 'Development'), ('Unplanned', 'Unplanned'), ('Internal QA', 'Internal QA'), ('Pull Request', 'Pull Request'), ('Client Review', 'Client Review'), ('review_fix', 'Review Fix'), ('merged', 'Merged'), ('qa_testing', 'QA Testing'), ('closed', 'Closed'), ('blocked', 'Blocked'), ('next_sprint', 'Next Sprint'), ('assigned_to_client', 'Assigned to Client'), ('infra_process', 'Infra Process')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_scope',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned')], max_length=20),
        ),
        migrations.AddField(
            model_name='effortrecord',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.SubTask'),
        ),
    ]
