# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_effortrecord_pr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprint',
            name='velocity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Development', 'Development'), ('Unplanned', 'Unplanned'), ('Internal QA', 'Internal QA'), ('Pull Request', 'Pull Request'), ('Client Review', 'Client Review'), ('Review Fix', 'Review Fix'), ('Merged', 'Merged'), ('QA Testing', 'QA Testing'), ('Closed', 'Closed'), ('Blocked', 'Blocked'), ('Next Sprint', 'Next Sprint'), ('Assigned to Client', 'Assigned to Client'), ('Infra Process', 'Infra Process')], max_length=20),
        ),
    ]
