# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_subtask_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codereview',
            name='sprint',
        ),
        migrations.AlterField(
            model_name='codereview',
            name='rca',
            field=models.CharField(choices=[('DOMO Standard', 'DOMO Standard'), ('AngularJS Experience', 'AngularJS Experience'), ('Client Code', 'Client Code'), ('Enhancement', 'Enhancement'), ('Code Optimization', 'Code Optimization'), ('Requirement Conflict', 'Requirement Conflict'), ('Reviewer Conflict', 'Reviewer Conflict'), ('Appreciation', 'Appreciation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='review_type',
            field=models.CharField(choices=[('Peer', 'Peer'), ('Client', 'Client'), ('QA', 'QA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='status',
            field=models.CharField(choices=[('Peer', 'Peer'), ('Client', 'Client'), ('QA', 'QA')], max_length=30),
        ),
    ]
