# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_codereview_review_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Fixed', 'Fixed'), ('Closed', 'Closed'), ('No Comments', 'No Comments')], max_length=30),
        ),
        migrations.AlterField(
            model_name='efforttracking',
            name='effort_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.EffortRecord'),
        ),
    ]
