# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0013_auto_20160127_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='efforttracking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
