# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20160127_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='team',
            field=models.CharField(choices=[('WETL', 'WETL'), ('Matrix', 'Matrix'), ('Gambit', 'Gambit'), ('Goonies', 'Goonies'), ('University', 'University')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.CharField(choices=[('WETL', 'WETL'), ('Matrix', 'Matrix'), ('Gambit', 'Gambit'), ('Goonies', 'Goonies'), ('University', 'University')], max_length=20, null=True),
        ),
    ]
