# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_auto_20160128_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_user_edit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Global Config',
            },
        ),
    ]
