# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_globalconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Keyword',
            },
        ),
    ]
