# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
