# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20160119_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effortrecord',
            name='client_review_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='effortrecord',
            name='closed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='effortrecord',
            name='code_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='effortrecord',
            name='internal_qa_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='effortrecord',
            name='peer_review_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='effortrecord',
            name='qa_testing',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='effortrecord',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
