# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20160119_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='effortrecord',
            name='pr_date',
            field=models.DateTimeField(null=True),
        ),
    ]
