# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_userprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='remaining',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
